name: Update readme.md

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Execute update script
        run: python create_readme.py
            
      - name: Commit changes
        run: |
          git config --global user.name 'jAniceto'
          git config --global user.email 'jAniceto@users.noreply.github.com'
          git commit -am "Updated readme.md"
          git push
          # git diff --exit-code || git commit -m "Updated readme.md" -a
